name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 8.0.2
homepage: https://github.com/fluttercandies/extended_image

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  extended_image_library:
    git:
      url: "https://github.com/waitwalker/extended_image_library.git"
  flutter:
    sdk: flutter
  meta: ^1.7.0
